### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by KyleKing** [casestudies/GeckoStepper#1]
Hi! I'm working on my first stepper motor project and I'm trying to use this library; however, I get this error:

```
In file included from GeckoStepper_oneStepAtATime.ino:1:
C:\Documents and Settings\Administrator\My Documents\Arduino\libraries\GeckoStepper/GeckoStepper.h:18:22: error: WProgram.h: No such file or directory
```

Would it be better to use the stepper library included with the IDE? I'm using the GeckoDrive G202 with a 4 strand linear actuator.

**Comment by casestudies** [comment]
I believe Arduino changed the include file from WProgram.h to something else. This was written with a pre-version 1.0 Arduino IDE, most likely the cause. This was more of an experiment for learning about creating a library. I got it to work, but you might be better off using the standard library included with the IDE.
